name: Auto Update Index
on:
  push:
    paths:
      - 'Ubuntu/**'
      - '2.5.3/**'
      - 'VFIFE/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run script
        run: python generate_index.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Auto-update index.html" || exit 0
          git push
